### ISSUE TITLE
duplicating sources in Data_Selection.ipynb

### ISSUE THREAD

**Issue by lgbouma** [Jurgenvilla/Gaia_DR2_ScoCen#2]
Hi! Thanks for putting out this research note -- it's super useful. Looking through the `Data_Selection.ipynb` notebook, there's something I didn't understand in the final cell:

```
RA = np.append(RA_DR2, RA_DR2); DEC = np.append(DEC_DR2, DEC_DR2)
l = np.append(l_DR2, l_DR2); b = np.append(b_DR2, b_DR2)
```

This duplicates the source coordinates, and leads to `/Data/DR2_PreMainSequence_SOURCE_IDS.csv` being twice as long as it should be.

Was there a logic behind this, or is it a bug?

Thanks for any clarification!
Luke

**Comment by Jurgenvilla** [comment]
Hi Luke,

Thanks for spotting this. Indeed, there's no point in saving the file that way. My bad! I wasn't so skilled during my master's. I would just simply save the RA, DEC and l,b from the vectors saved above directly. I'll just go for the easiest way of saving the data but I'm sure there are fancier ways to do it ;) 

np.savetxt('./Data/Coordinates_DR2_PreMainSequence".csv',\
           np.c_[RA_DR2, DEC_DR2, l_DR2, b_DR2], header = 'ra, dec, l, b',\
           fmt = ['%.15f','%.15f', '%.15f','%.15f'], delimiter = ',')

I hope it was useful!

cheers,
Jorge Villa

**Comment by lgbouma** [comment]
No worries -- thanks for the clarification :+1:
